# Numpy Practice session

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
#import numpy in this j.notebook
import numpy as np


# Creating an array using numpy

In [4]:
#1-D Array
import numpy as np
food = np.array(["Pakora", "Samosa","Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [5]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [6]:
type(price)

numpy.ndarray

In [7]:
type(food)

numpy.ndarray

In [8]:
len(price)

3

In [9]:
len(food)

3

In [11]:
price[2]

5

In [12]:
price[0:]

array([5, 5, 5])

In [14]:
food[1]

'Samosa'

In [15]:
price.mean()

5.0

In [16]:
# Zeros
np.zeros(0)

array([], dtype=float64)

In [17]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
# empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# specify the range
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [22]:
# specify the range with specific increment
np.arange(2,20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
#table
np.arange(5,55, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [27]:
# line space
np.linspace(0,100, num=10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [28]:
# specify your data type
np.ones(5, dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [30]:
# specify your data type
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Sorting (Array Functions)


In [34]:
a=np.array([10,21,24,100,35,300, 4.5])
a

array([ 10. ,  21. ,  24. , 100. ,  35. , 300. ,   4.5])

In [35]:
a.sort()
a

array([  4.5,  10. ,  21. ,  24. ,  35. , 100. , 300. ])

In [36]:
b=np.array([10.2,3.5,53.3,91.6,45.6])
b

array([10.2,  3.5, 53.3, 91.6, 45.6])

In [38]:
c =np.concatenate((a,b))
c

array([  4.5,  10. ,  21. ,  24. ,  35. , 100. , 300. ,  10.2,   3.5,
        53.3,  91.6,  45.6])

In [39]:
c.sort()
c

array([  3.5,   4.5,  10. ,  10.2,  21. ,  24. ,  35. ,  45.6,  53.3,
        91.6, 100. , 300. ])

# 2-D arrays

In [44]:
x = ([[1,2],[4,3]])
x

[[1, 2], [4, 3]]

In [46]:
y = np.array([[6,7],[8,9]])
y

array([[6, 7],
       [8, 9]])

In [48]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [4, 3],
       [6, 7],
       [8, 9]])

In [49]:
np.concatenate((x,y), axis=1)

array([[1, 2, 6, 7],
       [4, 3, 8, 9]])

In [50]:
a = np.array([[[0,1,2,3],[4,5,6,7]],
              [[0,1,2,3],[4,5,6,7]],
              [[0,1,2,3],[4,5,6,7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [51]:

#To find the numbers of dimenstions
a.ndim

3

In [53]:
b = np.array([[5,6,7],[8,9,10],[10,11,12]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [54]:
b.ndim

2

In [55]:
a.size

24

In [56]:
b.size

9

In [57]:
a.shape

(3, 2, 4)

In [60]:
a = np.arange(9) #3*3=9
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [61]:
# reshape
b = a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
# reshape
np.reshape (a, newshape =(1,9), order='c')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [63]:
# convert 1D array into 2d array
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
a.shape

(9,)

In [65]:
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [66]:
b.shape

(1, 9)

In [67]:
# Column wise
c = a[: , np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [68]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [70]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [71]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [73]:
a.sum()

45

In [74]:
a.mean()

5.0