In [3]:
import numpy as np
a = np.array([5,5,5,])
a

array([5, 5, 5])

In [4]:
type(a)

numpy.ndarray

In [7]:
#list of lists
b = np.array([[5,5,5], [5,5,5], [5,5,5]])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [8]:
import numpy as np
a = np.array([5,5,5,])
a


array([5, 5, 5])

In [9]:
type(a)

numpy.ndarray

In [10]:
len(a)

3

In [11]:
a[0]

5

In [12]:
a[0:]

array([5, 5, 5])

In [13]:
#list of lists
b = np.array([[5,5,5], [5,5,5], [5,5,5]])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [14]:
type(b)

numpy.ndarray

In [15]:
len(b)

3

In [16]:
b[0]

array([5, 5, 5])

In [17]:
b[0:]

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [18]:
c = np.array([[5,5,5], [5,5,5]])
c

array([[5, 5, 5],
       [5, 5, 5]])

In [19]:
import numpy as np
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [20]:
b = np.zeros(2)
b

array([0., 0.])

In [22]:
c = np.ones(3)
c

array([1., 1., 1.])

In [23]:
d = np.empty(3)
d

array([1., 1., 1.])

In [24]:
#with range of elements
e = np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [25]:
# with specific range of elements
f = np.arange(2, 20)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [26]:
#continue...
g = np.arange(2, 20, 2)
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
# linearly spaced arrays
h = np.linspace(0, 10,num=5) #gives use 5 nums
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [28]:
# specific data types in array
i = np.ones(5, dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [30]:
j = np.ones(3, dtype=np.float64)
j

array([1., 1., 1.])

In [31]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [33]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])